spring:
  application:
    name: tanzu-java-web-app
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
endpoints:
  server-app-url: ${SERVER_APP_URL}